/**
 * LangGraph Course Generator Workflow
 *
 * A 4-node state machine that:
 *   1. syllabusArchitect  — generates a 6 module course skeleton via Groq structured output,
 *                           persists Learning + Topics to MongoDB
 *   2. contextRetriever   — pulls top-3 semantic matches from knowledge_base via Atlas Vector Search
 *   3. contentWriter      — writes comprehensive Markdown (with LaTeX + code blocks) for the
 *                           current module, saves to Topic.contentMarkdown
 *   4. quizConstructor    — generates flashcard-style quiz items and saves to Topic.flashcards
 *
 * Flow:  START → syllabusArchitect → contextRetriever → contentWriter → quizConstructor
 *                                    ↑                                       │
 *                                    └───────── (loop if more modules) ──────┘
 *                                                                   or → END
 */

import { StateGraph, Annotation, END, START } from '@langchain/langgraph';
import { ChatGroq } from '@langchain/groq';
import { z } from 'zod';
import mongoose from 'mongoose';
import dbConnect from '../db.js';
import Learning from '../../models/Learning.js';
import Topic from '../../models/Topic.js';

import { embedText, chunkText } from '../embeddings.js';
import { KnowledgeBase } from '../../models/index.js';
import { invokeStructured } from '../groqHelper.js';

// ─── Groq LLM instances (lazy — avoids build-time crash if GROQ_API_KEY is unset)
let _groq = null;
let _groqCreative = null;

function getGroq() {
  if (!_groq) {
    _groq = new ChatGroq({
      model: 'llama-3.3-70b-versatile',
      temperature: 0.4,
      apiKey: process.env.GROQ_API_KEY,
    });
  }
  return _groq;
}

function getGroqCreative() {
  if (!_groqCreative) {
    _groqCreative = new ChatGroq({
      model: 'llama-3.3-70b-versatile',
      temperature: 0.7,
      apiKey: process.env.GROQ_API_KEY,
    });
  }
  return _groqCreative;
}

// ─── State Definition ──────────────────────────────────────────────────────
const CourseState = Annotation.Root({
  // Input fields
  topic: Annotation({
    reducer: (_prev, next) => next,
    default: () => '',
  }),
  targetAudience: Annotation({
    reducer: (_prev, next) => next,
    default: () => '',
  }),
  userId: Annotation({
    reducer: (_prev, next) => next,
    default: () => '',
  }),

  // Generated by syllabusArchitect
  learningId: Annotation({
    reducer: (_prev, next) => next,
    default: () => null,
  }),
  syllabus: Annotation({
    reducer: (_prev, next) => next,
    default: () => [],
  }),

  // Loop counter
  currentModuleIndex: Annotation({
    reducer: (_prev, next) => next,
    default: () => 0,
  }),

  // Accumulated content map: { topicId: markdownString }
  compiledContent: Annotation({
    reducer: (prev, next) => ({ ...prev, ...next }),
    default: () => ({}),
  }),

  // Transient context for the current iteration
  retrievedContext: Annotation({
    reducer: (_prev, next) => next,
    default: () => [],
  }),
});

// ─── Node 1: Syllabus Architect ─────────────────────────────────────────────

const syllabusSchema = z.object({
  modules: z.array(
    z.object({
      title: z.string().describe('Module title'),
      objectives: z.array(z.string()).describe('1-2 learning objectives for this module'),
      topics: z.array(z.string()).describe('Key topic keywords covered in this module'),
    })
  ).length(6).describe('Exactly 6 course modules'),
});

async function syllabusArchitect(state) {
  console.log('\n📐 [syllabusArchitect] Generating course skeleton...');
  console.log(`   Topic: "${state.topic}"`);
  console.log(`   Audience: "${state.targetAudience}"`);

  await dbConnect();

  const structuredGroq = getGroq().withStructuredOutput(syllabusSchema);

  const result = await invokeStructured(structuredGroq, [
    {
      role: 'system',
      content: `Create a structured 6-module syllabus for: "${state.topic}".
Progress logically. Target audience: ${state.targetAudience || 'general'}.
Each module needs a title, 1-2 objectives, and keywords.`,
    },
    {
      role: 'user',
      content: `Create a comprehensive course syllabus for: "${state.topic}"`,
    },
  ]);

  console.log(`   ✅ Generated ${result.modules.length} modules`);

  // Persist to MongoDB
  const learning = await Learning.create({
    title: state.topic,
    userId: state.userId || 'system',
  });

  console.log(`   💾 Created Learning: ${learning._id}`);

  const syllabus = [];

  for (let i = 0; i < result.modules.length; i++) {
    const mod = result.modules[i];
    const topic = await Topic.create({
      learningId: learning._id,
      title: mod.title,
      orderIndex: i,
      contentMarkdown: '',
      flashcards: [],
    });

    syllabus.push({
      title: mod.title,
      orderIndex: i,
      objectives: mod.objectives,
      topics: mod.topics,
      topicId: topic._id.toString(),
    });

    console.log(`   💾 Created Topic [${i}]: "${mod.title}" (${topic._id})`);
  }

  return {
    learningId: learning._id.toString(),
    syllabus,
    currentModuleIndex: 0,
  };
}

// ─── Node 2: Context Retriever ──────────────────────────────────────────────

async function contextRetriever(state) {
  const idx = state.currentModuleIndex;
  const mod = state.syllabus[idx];

  console.log(`\n🔍 [contextRetriever] Module ${idx}: "${mod.title}"`);

  await dbConnect();

  // Build a query string from the module's key concepts
  const queryText = [mod.title, ...mod.topics, ...mod.objectives].join('. ');

  console.log(`   Generating query embedding...`);
  const queryVector = await embedText(queryText);

  // Atlas Vector Search via native Mongoose aggregate

  let results = [];

  try {
    results = await KnowledgeBase.aggregate([
      {
        $vectorSearch: {
          index: 'vector_index',
          path: 'embedding',
          queryVector,
          numCandidates: 60,
          limit: 2,
        },
      },
      {
        $project: {
          _id: 0,
          textContent: 1,
          subjectCategory: 1,
          score: { $meta: 'vectorSearchScore' },
        },
      },
    ]);

    console.log(`   ✅ Retrieved ${results.length} context blocks from knowledge_base`);
    results.forEach((r, i) => {
      console.log(`      [${i + 1}] score=${r.score?.toFixed(4)} category="${r.subjectCategory}"`);
    });
  } catch (err) {
    // If Atlas Vector Search index doesn't exist yet, gracefully fall back
    console.warn(`   ⚠️  Vector search unavailable: ${err.message}`);
    console.log(`   Proceeding without retrieved context.`);
  }

  return {
    retrievedContext: results.map((r) => r.textContent || ''),
  };
}

// ─── Node 3: Content Writer ─────────────────────────────────────────────────

async function contentWriter(state) {
  const idx = state.currentModuleIndex;
  const mod = state.syllabus[idx];

  console.log(`\n✍️  [contentWriter] Writing content for Module ${idx}: "${mod.title}"`);

  await dbConnect();

  // Build a context block from retrieved vectors
  const contextBlock =
    state.retrievedContext.length > 0
      ? `\n\n## Reference Material\n${state.retrievedContext
          .map((c, i) => `### Source ${i + 1}\n${c}`)
          .join('\n\n')}`
      : '';

  const response = await getGroqCreative().invoke([
    {
      role: 'system',
      content: `Act as a technical educator. Write a focused explanation of 300-500 words in Markdown (no top-level # title).
Target audience: ${state.targetAudience || 'general learners'}.
Requirements:
- Heading hierarchy (## sections, ### subsections).
- Inline equations wrapped in $...$, block in $$...$$.
- Descriptive, runnable code blocks.
- Real-world analogies and examples.`,
    },
    {
      role: 'user',
      content: `Write comprehensive course content for the module: "${mod.title}"

Learning objectives:
${mod.objectives.map((o) => `- ${o}`).join('\n')}

Key topics to cover:
${mod.topics.map((t) => `- ${t}`).join('\n')}
${contextBlock}`,
    },
  ]);

  const markdown = response.content;

  // Persist to MongoDB
  await Topic.findByIdAndUpdate(mod.topicId, {
    contentMarkdown: markdown,
  });

  // Save chunks to RAG KnowledgeBase
  try {
    // Clean up old RAG entries for this topic first
    await KnowledgeBase.deleteMany({ topicId: mod.topicId });

    // Chunk and generate embeddings
    const chunks = chunkText(markdown, 1000, 200);
    for (const chunk of chunks) {
      const embedding = await embedText(chunk);
      await KnowledgeBase.create({
        textContent: chunk,
        embedding,
        subjectCategory: state.topic || 'generated',
        topicId: mod.topicId,
      });
    }
    console.log(`   ✅ Ingested ${chunks.length} chunks into RAG KnowledgeBase for topic ${mod.topicId}`);
  } catch (ragErr) {
    console.error(`   ⚠️ Failed to ingest generated topic to RAG KnowledgeBase:`, ragErr);
  }

  console.log(`   ✅ Written ${markdown.length} chars → Topic ${mod.topicId}`);

  return {
    compiledContent: { [mod.topicId]: markdown },
  };
}

// ─── Node 4: Quiz Constructor ───────────────────────────────────────────────

const quizSchema = z.object({
  flashcards: z.array(
    z.object({
      front: z.string().describe('The question or concept prompt'),
      back: z.string().describe('The answer or explanation'),
    })
  ).describe('5-8 flashcard-style quiz items'),
});

async function quizConstructor(state) {
  const idx = state.currentModuleIndex;
  const mod = state.syllabus[idx];
  const content = state.compiledContent[mod.topicId] || '';

  console.log(`\n🧠 [quizConstructor] Generating quiz for Module ${idx}: "${mod.title}"`);

  await dbConnect();

  const structuredGroq = getGroq().withStructuredOutput(quizSchema);

  const result = await invokeStructured(structuredGroq, [
    {
      role: 'system',
      content: `Create 5-8 flashcard questions testing the provided content.
Format:
- "front": clear question or concept prompt.
- "back": concise, complete answer/explanation.
Mix factual recall, conceptual understanding, and application scenarios.`,
    },
    {
      role: 'user',
      content: `Generate review flashcards for this course module:

Module: "${mod.title}"

Content:
${content.slice(0, 6000)}`,
    },
  ]);

  // Persist flashcards to MongoDB
  await Topic.findByIdAndUpdate(mod.topicId, {
    flashcards: result.flashcards,
  });

  console.log(`   ✅ Generated ${result.flashcards.length} flashcards → Topic ${mod.topicId}`);

  return {};
}

// ─── Flow Control Router ────────────────────────────────────────────────────

function shouldContinue(state) {
  const nextIndex = state.currentModuleIndex + 1;
  const totalModules = state.syllabus.length;

  if (nextIndex < totalModules) {
    console.log(`\n🔄 [router] Module ${state.currentModuleIndex} complete. Advancing to ${nextIndex}/${totalModules - 1}`);
    return 'continue';
  }

  console.log(`\n🏁 [router] All ${totalModules} modules complete. Finishing.`);
  return 'finish';
}

// Increment node — bumps the counter before looping back
async function incrementModule(state) {
  return {
    currentModuleIndex: state.currentModuleIndex + 1,
  };
}

// ─── Graph Assembly ─────────────────────────────────────────────────────────

const workflow = new StateGraph(CourseState)
  // Register nodes
  .addNode('syllabusArchitect', syllabusArchitect)
  .addNode('contextRetriever', contextRetriever)
  .addNode('contentWriter', contentWriter)
  .addNode('quizConstructor', quizConstructor)
  .addNode('incrementModule', incrementModule)

  // Linear flow: START → syllabusArchitect → contextRetriever → contentWriter → quizConstructor
  .addEdge(START, 'syllabusArchitect')
  .addEdge('syllabusArchitect', 'contextRetriever')
  .addEdge('contextRetriever', 'contentWriter')
  .addEdge('contentWriter', 'quizConstructor')

  // Conditional loop: quizConstructor → (increment → contextRetriever) OR END
  .addConditionalEdges('quizConstructor', shouldContinue, {
    continue: 'incrementModule',
    finish: END,
  })
  .addEdge('incrementModule', 'contextRetriever');

// Compile the graph
const courseGraph = workflow.compile();

export { courseGraph, CourseState };
export default courseGraph;
